### PR TITLE
Add crossorigin flag for textures

### LINKED ISSUE #12: CORS - Textures and Tained canvas
Problem
---
Images downloaded as textures seems not to use `crossOrigin = "Anonymous"` flag and they make my canvas tained.

Reproduce
---

I've created this Ellie (https://ellie-app.com/86XKmYD9Mxya1) that loads a texture, just popup the browser console and execute this

```javascript
var tmpCtx=document.createElement("canvas").getContext("2d");
tmpCtx.drawImage(document.querySelectorAll("img[src='https://www.alsipnursery.com/wp-content/uploads/2019/04/1703190.jpg']")[0],0,0);
tmpCtx.getImageData(1,1,1,1);
```

You can see that on my project https://kubaracek.github.io/hanggliding-map/ that uses map tiles

```javascript
var tmpCtx=document.createElement("canvas").getContext("2d");
tmpCtx.drawImage(document.querySelectorAll("img[src='https://tile.nextzen.org/tilezen/terrain/v1/256/terrarium/11/1087/715.png?api_key=Nl9_q6yZQA6NIJp6Zn9kYg']")[0],0,0);
tmpCtx.getImageData(1,1,1,1);
```

Interesting this is that on my project the image returns: `access-control-allow-origin: *`

### PR DESCRIPTION
**Pull request by kubaracek**
This should resolve canvas taining because of CORS
Fixes #12

### CODE REVIEW

**Comment by kubaracek** [comment]
I've tested that by just simply creating an image in my elm project with

```elm
img [ Attr.attribute "crossorigin" "anonymous"
       ,Attr.src "https://www.alsipnursery.com/wp-content/uploads/2019/04/1703190.jpg"
       ] []
```

I was then able to get the canvas data

**Comment by kubaracek** [comment]
It's still behaving somewhat funny. With my project it works when I open a new window and load it the first time but get the tained cors problem when I refresh.

**Comment by joakin** [comment]
I've read https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/crossOrigin and https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin and I don't see any gotchas to adding the attribute. If anything it will avoid external image requests getting credentials, so sounds good to me.

Is this ready to merge or do you want to look at your problem some more?

**Comment by kubaracek** [comment]
@joakin This seems to fix the issue in general way. I still need to dig into why it behaves weird my project. Will try to look at this at some point this week but it's probably something on my side. This crossorigin canvas thing is not very well supported in the browsers yet as each behave differently.

**Pull request merged**
